### ISSUE TITLE
Machine Learning lynda project files.

### ISSUE THREAD

**Issue by rodolfoleal** [callmecary/research#1]
Hi @callmecary 

Please could you share the original files from Lynda Machine learning project, if you could provide the .csv would be great.

This would help me a lot, i couldnt download that.

Thanks a lot.

**Comment by callmecary** [comment]
Happy to help, but first can you be more specific on which csv you are referring to. My research repo is like a sandbox contains things here and there.

**Comment by rodolfoleal** [comment]
From 
Ex_Files_TensorFlow/Ex_Files_TensorFlow/Exercise Files

the .number in csv format.

Would be great. Thanks buddy.

**Comment by callmecary** [comment]
[06.zip](https://github.com/callmecary/research/files/1682523/06.zip)

**Comment by rodolfoleal** [comment]
Thanks Very much
Close #1
